version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      # - 9092:9092
      - 9093:9093
    expose:
      - "9093"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="kafka_capstone_event_bus:1:1"
      - KAFKA_CFG_AUTO_CREATE_TOPIBS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092, EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092, EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    
    # environment:
    #   - KAFKA_BROKER_ID=1
    #   - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    #   - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    #   - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #   - ALLOW_PLAINTEXT_LISTENER=yes
    #   - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
    #   - KAFKA_CFG_LISTENERS=CLIENT://:9092
    #   - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
    #   - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    # depends_on:
    #   - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    # restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka
